[package]
name        = "rscenes"
version     = "0.1.3"
authors     = ["Rodrigo Montegasppα Cacilhας <montegasppa@cacilhas.info"]
license     = "BSD-3-Clause"
readme      = "README.md"
homepage    = "https://github.com/cacilhas/rscenes"
repository  = "https://github.com/cacilhas/rscenes"
keywords    = ["raylib", "scenes"]
description = "Scenes manager for Raylib"
edition     = "2021"

[dependencies]
anyhow = "1.0"
raylib = "3.7"
thiserror = "1.0"
