[package]
name          = "rscenes"
version       = "0.1.6"
authors       = ["Rodrigo Montegasppα Cacilhας <montegasppa@cacilhas.info"]
license       = "BSD-3-Clause"
readme        = "README.md"
documentation = "https://docs.rs/rscenes"
homepage      = "https://github.com/cacilhas/rscenes"
repository    = "https://github.com/cacilhas/rscenes"
keywords      = ["raylib", "scenes"]
description   = "Scenes manager for Raylib"
edition       = "2021"

[lib]
name = "rscenes"
path = "src/lib.rs"
documentation = true

[dependencies]
anyhow = "1.0"
raylib = "3.7"
thiserror = "1.0"
