[package]
name          = "rscenes"
version       = "2.0.0"
authors       = ["Rodrigo Montegasppα Cacilhας <montegasppa@cacilhas.info"]
license       = "BSD-3-Clause"
readme        = "../README.md"
description   = "Scenes manager for Raylib."
documentation = "https://crates.io/crates/rscenes"
repository    = "https://github.com/cacilhas/rscenes"
homepage      = "https://crates.io/crates/rscenes"
categories    = ["api-bindings", "game-engines", "graphics"]
keywords      = ["raylib", "scenes"]
edition       = "2021"

[dependencies.rscenes-macros]
version = "1.0"
path = "../rscenes-macros"

[dependencies.rscenes-raylib-connector]
version = "1.0"
path = "../rscenes-raylib-connector"
